-- Drop Tables
DROP TABLE IF EXISTS discount_orders CASCADE;
DROP TABLE IF EXISTS bag_orders CASCADE;
DROP TABLE IF EXISTS cargo_orders CASCADE;
DROP TABLE IF EXISTS product_orders CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
